### ISSUE TITLE
Extend possibility to configure database port

### ISSUE THREAD

**Issue by d-cordes** [qrioniclabs/homeassistant-mysql_command#7]
Hi,

thank you very much for creating and sharing this homeassistant add-on. My database uses a different port than 3306. Therefore, I extended your current implementation by an additional parameter. If you like, I can share my extension on, e.g., a different branch.

Best regards,
Daniel

**Comment by qrioniclabs** [comment]
Hi! Thank you for the suggestion! I completely ignored the fact that my component only supports the default port. I guess I thought that the Python MySQL Connector would accept a port as part of the host parameter. Thanks for offering to share, but I think I will implement this on my own, it will be just a few lines + documentation. I will update the repository this week.

**Comment by qrioniclabs** [comment]
Hey, @d-cordes! The custom component has been updated to 1.2.0 to include your suggestion. Thank you!

**Comment by d-cordes** [comment]
@qrioniclabs: Thanks a lot for your support. Works as expected.
